---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04
    driver_config:
      box: opscode-ubuntu-14.04
  - name: centos-6.4
    driver_config:
      box: opscode-centos-6.4

suites:
  - name: "debian-default"
    run_list:
      - recipe[gotcms]
    excludes:
      - centos-6.4
      - centos-5.9

  - name: "redhat-default"
    run_list:
      - recipe[gotcms]
    excludes:
      - ubuntu-14.04
      - ubuntu-12.04

  - name: "debian-postgresql"
    run_list:
      - recipe[gotcms]
    excludes:
      - centos-6.4
      - centos-5.9
    attributes:
      gotcms:
        db:
          driver: 'pdo_pgsql'
      postgresql:
        password:
          postgres: 'toor'

  - name: "redhat-postgresql"
    run_list:
      - recipe[gotcms]
    excludes:
      - ubuntu-14.04
      - ubuntu-12.04
    attributes:
      gotcms:
        db:
          driver: 'pdo_pgsql'
