---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-13.04
    driver_config:
      box: opscode-ubuntu-13.04
      box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box
  - name: centos-6.4
    driver_config:
      box: opscode-centos-6.4
      box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
  - name: "debian-default"
    run_list:
      - recipe[gotcms]
    excludes:
      - centos-6.4
      - centos-5.9

  - name: "redhat-default"
    run_list:
      - recipe[gotcms]
    excludes:
      - ubuntu-13.04
      - ubuntu-12.04

  - name: "debian-postgresql"
    run_list:
      - recipe[gotcms]
    excludes:
      - centos-6.4
      - centos-5.9
    attributes:
      gotcms:
        db:
          driver: 'pdo_pgsql'
      postgresql:
        password:
          postgres: 'toor'

  - name: "redhat-postgresql"
    run_list:
      - recipe[gotcms]
    excludes:
      - ubuntu-13.04
      - ubuntu-12.04
    attributes:
      gotcms:
        db:
          driver: 'pdo_pgsql'
