AllCops:
  Include:
    - metadata.rb
    - '**/Gemfile'
    - attributes/**/*
    - providers/**/*
    - resources/**/*
    - libraries/**/*
    - recipes/**/*
    - spec/**/*
  Exclude:
    - cookbooks/**/*
    - vendor/**/*

Encoding:
  Exclude:
    - metadata.rb
    - Gemfile

NumericLiterals:
  Enabled: false

LineLength:
  Enabled: false

WordArray:
  MinSize: 3

CyclomaticComplexity:
  Exclude:
    - libraries/**/*
    - providers/**/*
    - resources/**/*

MethodLength:
  Exclude:
    - libraries/**/*
    - providers/**/*
    - resources/**/*
